# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - familytree

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: npm install and build
      run: |
        npm install
        CI=false npm run build --if-present
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
          app-name: 'familytree'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_67BB29728E4144619FB6EDFBC1CC583F }}
          package: ./build
